version: '3'

volumes:
  db-data:

services:
  db:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    env_file: db.env
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    image: 'node:18'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  backend:
    image: 'eclipse-temurin:17'
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
