version: '3'

volumes:
  db-data:

services:
  db:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    env_file: db.env
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    image: 'node:18'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '24678:24678'
    environment:
      - API_HOST=backend # docker perspective -- inside
      - API_PORT=8080 # docker perspective -- left port

  backend:
    image: 'eclipse-temurin:17'
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8080'
    env_file: db.env
    environment:
      - DATABASE_HOST=db # docker perspective -- inside
      - DATABASE_PORT=5432 # docker perspective -- left
