version: '3'
services:
  db:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    env_file: db.env

  backend:
    image: 'openjdk:17'
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
    env_file: db.env

  frontend:
    image: 'node:18'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
