/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ImageEntity
 */
export interface ImageEntity {
    /**
     * 
     * @type {number}
     * @memberof ImageEntity
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ImageEntity
     */
    imageUrl: string;
    /**
     * 
     * @type {number}
     * @memberof ImageEntity
     */
    width: number;
    /**
     * 
     * @type {number}
     * @memberof ImageEntity
     */
    height: number;
    /**
     * 
     * @type {string}
     * @memberof ImageEntity
     */
    description?: string;
}
